outputs  = ["It is certain.",
            "It is decidedly so.",
            "Without a doubt.",
            "Yes - definitely.",
            "You may rely on it.",
            "As I see it, yes.",
            "Most likely.",
            "Outlook good.",
            "Yes.",
            "Signs point to yes.",
            "Reply hazy, try again.",
            "Ask again later.",
            "Better not tell you now.",
            "Cannot predict now.",
            "Concentrate and ask again.",
            "Don't count on it.",
            "My reply is no.",
            "My sources say no.",
            "Outlook not so good.",
            "Very doubtful.",
            "Maybe.",
            "Because yes.",
            "E.",
            "Idk man, idk.",
            "Huh? Are you asking me?",
            "Come back tomorrow",
            "Amazing. Every word of what you just said was wrong.",
            "🍿",
            "Ok, but did I ask?",
            "Ok and?"]